<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260220214141 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('ALTER TABLE analysis DROP CONSTRAINT fk_analysis_game');
        $this->addSql('ALTER TABLE analysis ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE analysis ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE analysis ALTER depth DROP DEFAULT');
        $this->addSql('ALTER TABLE analysis ALTER status DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN analysis.created_at IS \'\'');
        $this->addSql('ALTER TABLE analysis ADD CONSTRAINT FK_33C730E48FD905 FOREIGN KEY (game_id) REFERENCES game (id) NOT DEFERRABLE');
        $this->addSql('ALTER INDEX idx_analysis_game_id RENAME TO IDX_33C730E48FD905');
        $this->addSql('ALTER TABLE game ADD owner_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE game ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE game ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN game.created_at IS \'\'');
        $this->addSql('ALTER TABLE game ADD CONSTRAINT FK_232B318C7E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id)');
        $this->addSql('CREATE INDEX IDX_232B318C7E3C61F9 ON game (owner_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE "user"');
        $this->addSql('ALTER TABLE analysis DROP CONSTRAINT FK_33C730E48FD905');
        $this->addSql('ALTER TABLE analysis ALTER id SET DEFAULT nextval(\'analysis_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE analysis ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE analysis ALTER depth SET DEFAULT 20');
        $this->addSql('ALTER TABLE analysis ALTER status SET DEFAULT \'pending\'');
        $this->addSql('COMMENT ON COLUMN analysis.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE analysis ADD CONSTRAINT fk_analysis_game FOREIGN KEY (game_id) REFERENCES game (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX idx_33c730e48fd905 RENAME TO idx_analysis_game_id');
        $this->addSql('ALTER TABLE game DROP CONSTRAINT FK_232B318C7E3C61F9');
        $this->addSql('DROP INDEX IDX_232B318C7E3C61F9');
        $this->addSql('ALTER TABLE game DROP owner_id');
        $this->addSql('ALTER TABLE game ALTER id SET DEFAULT nextval(\'game_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE game ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN game.created_at IS \'(DC2Type:datetime_immutable)\'');
    }
}
